schema_version = "1.0.0"

id = "if0xit_bim_toolbox_theme_neon_light_b4"
version = "1.1.0"
name = "BIM Toolbox Neon Light (B4)"
tagline = "Modern neon light theme for Blender 4.x"
maintainer = "iF0xit"
type = "theme"
website = "https://github.com/iF0xit/bim-toolbox-theme-neon"

blender_version_min = "4.2.0"
blender_version_max = "4.9.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

[permissions]
